# base url used to resolved all internal links with pages and resources
# set it empty when testing on local
# set it to https://user.github.io/project before publishing
baseurl: http://mistic100.github.io/Bootstrap-Confirmation

# name of the software
name: Bootstrap Confirmation
# current version of the software
version: 2.0.0
# url of the download button
downloadUrl: https://github.com/mistic100/Bootstrap-Confirmation
# licence of the software
license: Apache License v2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

# list of additional links on the right of the top menu
headerLinks:
  - title: StrangePlanet
    url: http://www.strangeplanet.fr

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/Bootstrap-Confirmation
  - title: Issues
    url: https://github.com/mistic100/Bootstrap-Confirmation/issues?state=open

# github button
githubButton:
  user: mistic100
  repo: Bootstrap-Confirmation

# twitter follow button
twitterAccount:

# url for tweet button
shareUrl:

# google analytics
analytics:
  account: UA-28192323-3
  domain: mistic100.github.io


# DON'T MODIFY
pygments: true
highlight: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']