# name of the software
name: Bootstrap Confirmation
# current version of the software
version: 2.2.0
# url of the download button
downloadUrl: https://github.com/mistic100/Bootstrap-Confirmation
# licence of the software
license: Apache License v2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/mistic100/Bootstrap-Confirmation
  - title: StrangePlanet
    url: http://www.strangeplanet.fr

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/Bootstrap-Confirmation
  - title: Issues
    url: https://github.com/mistic100/Bootstrap-Confirmation/issues?state=open

# header
header:
  color1: "#009ece"
  color2: "#003354"
  trianglify: true

# github button
githubButton:
  user: mistic100
  repo: Bootstrap-Confirmation

# twitter buttons
twitter:
  enabled: true
  via: mistic100
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:

# google analytics
analytics:
  account: UA-28192323-3
  domain: mistic100.github.io


# DON'T MODIFY
pygments: true
highlight: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']